# Generated by Django 5.0.6 on 2024-06-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_blocklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockList',
            new_name='BlockedList',
        ),
    ]
